import { Metadata } from 'next';

import { Navigation, OrgSidebar, Sidebar } from '@/_components/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex-auto">
      <Sidebar />
      <div className="h-full pl-16">
        <div className="flex h-full">
          <OrgSidebar />
          <div className="h-full flex-1">
            <Navigation />
            {children}
          </div>
        </div>
      </div>
    </main>
  );
}
